#!/bin/sh

# Copyright (C) 2021  Plaunarome
# This file is part of Plaunadots.
#
# Plaunadots is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Plaunadots is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Plaunadots.  If not, see <https://www.gnu.org/licenses/>.

[ -z "$HOME" ] && { >&2 echo "The environment variable \$HOME is required, but it is unset or empty."; exit 1; }
export PATH="${HOME}/.local/bin:${PATH}"

export BROWSER="xdg-open"
export EDITOR="nvim"

for program in "$BROWSER" "$EDITOR"; do
	[ -x "$(command -v -- "$program")" ] && continue
	>&2 echo "The program \"${program}\" is required, but it was not found or it is not executable."
	exit 1
done

# -- XDG directories -- #
export XDG_CACHE_HOME="${XDG_CACHE_HOME:-${HOME}/.cache}"
export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-${HOME}/.config}"
export XDG_DATA_HOME="${XDG_DATA_HOME:-${HOME}/.local/share}"

mkdir --mode 700 --parents -- "$XDG_CACHE_HOME" "$XDG_CONFIG_HOME" "$XDG_DATA_HOME" || exit 1

# -- XDG workarounds -- #
export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/pass"
